### ISSUE TITLE
Can you please explain this linter to me?

### ISSUE THREAD

**Issue by frederikhors** [gostaticanalysis/fourcetypeassert#7]
I'm learning Go.

Can you please explain this linter to me?

I'm using interface assertion. It says to me: "`type assertion must be checked (forcetypeassert)`".

What does this mean?

What should I do?

**Comment by ozon2** [comment]
I had the same problem, it would be nice if the readme gave a solution to its example.
I found that you need to check the second value returned by the type assertion:
```go
_, ok = a.(int)
if !ok {
  // handle error
}
```
